In [39]:
import pandas as pd
import numpy as np
import time
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
from fcmeans import FCM
from matplotlib import pyplot as plt

In [9]:
df = pd.read_csv('All_pecanoy_layer.txt', sep="\t")

In [14]:
#df.rows = df.iloc[:,0]
df = df.set_index('gid')

,GRN_V2,GRN_V3,GRN_V4,GRN_V5,GRN_V6,GRN_V7,GRN_V8,GRN_V9,GRN_V10,GRN_V11,...,GAN_V92,GAN_V93,GAN_V94,GAN_V95,GAN_V96,GAN_V97,GAN_V98,GAN_V99,GAN_V100,GAN_V101
gid,,,,,,,,,,,,,,,,,,,,,
Zm00001d026095,0.709605,0.077195,-1.448861,-0.775455,-0.436365,0.310434,0.139175,-1.129219,0.805108,1.068330,...,0.594613,-1.647158,-0.861722,-1.048696,-0.661585,-0.211395,-0.846997,-1.434209,-1.238600,-1.315265
Zm00001d026094,-1.523115,1.496695,-0.636356,-1.737615,0.201688,-1.402617,1.088773,-1.925271,-1.408953,-1.444178,...,-1.081263,0.689109,-1.515221,0.926113,1.398508,-0.171407,0.156936,-0.949317,-0.091481,-0.378247
Zm00001d018822,1.068294,0.483063,0.830025,-1.285197,-0.496320,1.376892,-1.617763,-0.458064,-1.230526,-1.454982,...,-1.467715,-0.381656,-0.416343,-0.819506,-1.481632,2.519804,-0.235274,-0.315394,1.594985,0.443756
Zm00001d026079,0.067331,0.133538,0.324237,1.619394,-0.949942,1.185386,-0.319710,-0.850495,0.847364,-0.856855,...,-0.198351,0.639625,1.304442,0.785010,0.890937,-0.562792,0.341273,-1.921800,0.509447,1.574816
Zm00001d038513,1.348356,0.132660,-0.342586,-1.070728,-0.825761,-1.286262,-0.542265,1.262898,1.339073,-0.581774,...,0.837772,-0.421961,-0.678934,0.487620,-0.610857,1.670222,-0.195271,-0.888828,1.205869,0.044198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zm00001d041549,-0.827944,1.418371,0.536493,0.880953,-1.759659,0.336479,0.648534,-0.744494,-1.452773,0.188190,...,0.990297,-0.349862,0.850032,1.716376,-0.250759,0.119638,-0.310914,-0.130898,-0.608095,1.225615
Zm00001d024532,0.263191,1.170787,1.038568,-0.674011,0.351125,-1.743423,-1.420616,0.660507,1.115969,0.332946,...,-1.773617,-0.210189,-3.018870,-0.603563,-1.216419,-0.034864,1.024880,-0.734238,-0.928877,0.921869
Zm00001d045600,0.198222,-0.081667,-0.781605,-0.554501,-1.883669,-1.368454,0.873471,-0.476641,-1.353236,-0.335793,...,0.137105,0.284302,0.879249,0.303018,-0.712567,0.824619,-0.412020,-1.191353,1.479804,-1.350296
Zm00001d015585,1.337438,-1.535611,-1.515278,1.219639,1.250822,-0.186019,-1.296817,-1.400123,1.474860,-0.482804,...,0.226755,0.950310,-1.076594,1.482309,-0.224503,-1.550862,-0.725154,-1.238833,0.500393,2.085161
Zm00001d049884,1.089403,1.048964,-1.428951,0.339084,1.087944,1.300146,-0.352540,-0.725406,-0.243292,-0.451757,...,1.328252,-1.112447,-0.424492,0.529190,-1.822585,0.489512,0.462063,0.318415,0.179484,0.954245

In [42]:
#dftem = df.iloc[0:10000,:]

start_time = time.time()

cosdf = cosine_similarity(df)

print("--- %s seconds ---" % (time.time() - start_time))

cosdf

--- 6.17894434928894 seconds ---

array([[ 1.00000000e+00, -5.69396043e-02, -2.35358333e-02, ...,
        -8.63022465e-02, -4.84641305e-02,  7.19854023e-02],
       [-5.69396043e-02,  1.00000000e+00, -6.29046717e-03, ...,
         2.88391660e-02,  1.33509070e-01, -1.28305343e-01],
       [-2.35358333e-02, -6.29046717e-03,  1.00000000e+00, ...,
        -1.21329844e-02, -6.85318693e-02,  1.17636672e-01],
       ...,
       [-8.63022465e-02,  2.88391660e-02, -1.21329844e-02, ...,
         1.00000000e+00,  3.86990157e-02, -2.82732180e-04],
       [-4.84641305e-02,  1.33509070e-01, -6.85318693e-02, ...,
         3.86990157e-02,  1.00000000e+00, -1.79517598e-02],
       [ 7.19854023e-02, -1.28305343e-01,  1.17636672e-01, ...,
        -2.82732180e-04, -1.79517598e-02,  1.00000000e+00]])

In [28]:
pd.DataFrame(cosdf, columns = df.index , index = df.index).to_csv("CosMatrix_All_layer.txt", sep='\t')

In [1]:
cosdf.shape

NameError: name 'cosdf' is not defined

In [36]:
n_samples = 3000

X = np.concatenate((
    np.random.normal((-2, -2), size=(n_samples, 2)),
    np.random.normal((2, 2), size=(n_samples, 2))
))

In [2]:
X = df.to_numpy()
X

NameError: name 'df' is not defined

In [51]:
fcm = FCM(n_clusters=100)

fcm.fit(df.to_numpy())

In [83]:
# outputs
fcm_centers = fcm.centers
fcm_labels = fcm.predict(df.to_numpy())

In [77]:
# plot result
f, axes = plt.subplots(1, 2, figsize=(11,5))
axes[0].scatter(X[:,0], X[:,1], alpha=.1)
axes[1].scatter(X[:,0], X[:,1], c=fcm_labels, alpha=.1)
axes[1].scatter(fcm_centers[:,0], fcm_centers[:,1], marker="+", s=500, c='w')
#plt.savefig('images/basic-clustering-output.jpg')
plt.show()

(100, 300)

In [89]:
# make df with labes and gene ids
out = pd.DataFrame({'GeneID':df.index, 'Module':fcm_labels}) 
out.to_csv("CmeanGroupsPy.txt", sep='\t')

In [59]:
# Count Freq
#y = np.bincount(fcm_labels)
#ii = np.nonzero(y)[0]
#np.vstack((ii,y[ii]))

In [84]:
fcm_labels.shape

(23030,)

In [85]:
fcm_labels

array([80, 95, 78, ..., 70, 21, 48])

In [88]:
#fcm.u[fcm_labels==80,:]

In [81]:
df.loc[fcm_labels==80,:]

,GRN_V2,GRN_V3,GRN_V4,GRN_V5,GRN_V6,GRN_V7,GRN_V8,GRN_V9,GRN_V10,GRN_V11,...,GAN_V92,GAN_V93,GAN_V94,GAN_V95,GAN_V96,GAN_V97,GAN_V98,GAN_V99,GAN_V100,GAN_V101
gid,,,,,,,,,,,,,,,,,,,,,
Zm00001d026095,0.709605,0.077195,-1.448861,-0.775455,-0.436365,0.310434,0.139175,-1.129219,0.805108,1.068330,...,0.594613,-1.647158,-0.861722,-1.048696,-0.661585,-0.211395,-0.846997,-1.434209,-1.238600,-1.315265
Zm00001d045784,-1.707093,-1.108013,-1.468470,-0.951320,-0.059800,-1.304078,-0.109816,-0.608009,-1.806101,-0.007759,...,0.953982,0.198801,-0.377439,-1.759295,-1.106728,1.156192,-0.847572,-0.317944,-0.038188,-0.937165
Zm00001d036337,0.143861,1.265546,0.070727,-0.303730,1.151955,-0.483454,1.462285,1.608165,-0.103793,1.383509,...,1.502448,0.906381,0.459218,0.661640,-0.070358,0.438694,2.254872,-1.064511,-1.238739,-0.843751
Zm00001d039324,0.446831,1.478566,-1.708466,-1.589598,0.935882,0.982493,1.653435,-0.919099,0.919452,-1.024592,...,-0.098732,-0.286727,-0.123085,0.355111,-1.934069,2.000532,1.088135,0.741960,0.732356,0.503517
Zm00001d045838,-1.545968,-1.474550,-1.508338,-1.286911,-1.540234,-0.295780,-1.207187,0.939394,-0.034907,-0.302275,...,0.561889,0.151303,0.467398,1.223940,-0.999382,-0.738558,-0.687666,-0.067298,-0.217187,0.429956
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zm00001d053427,0.105254,0.581557,0.049772,0.258633,0.816342,-1.313809,1.348791,-0.485410,-1.498145,0.728984,...,0.530956,-1.707072,0.490242,-0.078887,1.254668,2.787663,1.423939,-0.467258,-0.809158,-0.826500
Zm00001d038473,0.810995,-1.088015,-0.383272,-1.490148,-0.701281,1.437815,0.135327,-1.276012,-0.771415,1.329915,...,-1.405747,-1.035818,-0.968106,-0.792469,0.728605,0.737943,-1.370060,-0.811744,-1.320843,-0.446744
Zm00001d032492,-1.461108,1.608622,0.018653,-0.358496,0.675348,0.486052,0.611056,0.188947,1.095252,0.442119,...,-0.639358,0.182378,-0.337587,-0.096935,0.033533,0.130151,0.105414,-0.307467,0.780841,-0.996573
Zm00001d024709,-1.539392,-1.374360,0.506718,0.821326,-1.118112,-0.931770,-1.501216,1.136675,-0.172823,-1.092637,...,0.621380,-0.590648,-0.051448,1.144961,-1.928685,0.853378,-0.245794,0.815129,0.767186,-1.039872
Zm00001d015936,-0.703657,-1.411245,1.532678,-1.226054,0.208023,1.764086,-0.238316,1.438283,-1.584037,0.106441,...,-0.637034,1.406640,-0.075537,0.660770,-0.164205,-0.416857,-0.075817,-1.217138,1.167670,-0.355679

In [82]:
cosdf[fcm_labels==80,:]

array([[ 1.        , -0.0569396 , -0.02353583, ..., -0.08630225,
        -0.04846413,  0.0719854 ],
       [ 0.07945252,  0.05379923, -0.00835419, ...,  0.04861825,
        -0.02193531,  0.10823825],
       [ 0.05319726, -0.06004527, -0.04920768, ..., -0.01667154,
        -0.06737874,  0.02270598],
       ...,
       [ 0.02734043,  0.10110264, -0.02775227, ..., -0.05324504,
        -0.02762553,  0.01116597],
       [-0.01838573,  0.04081709,  0.04906258, ...,  0.05201841,
         0.00468127, -0.05473769],
       [ 0.02784773,  0.02748471,  0.03233067, ...,  0.10502173,
        -0.04115352,  0.04239073]])